#!/bin/bash

CURPATH=`pwd`

if [ ! $1 ];
then
	echo "Usage: $0 <server IP> <server port>"
	echo "$0 eth0 9000"
	exit 1;
fi

if [ ! $2 ];
then
	echo "Usage: $0 <server IP> <erver port>"
	echo "$0 eth0 9000"
	exit 1;
fi

cd /home/wwjia/vPair/apps/clamav/build
IP=`ifconfig $1 | perl -nle'/inet addr:(\S+)/ && print $1'`
sed '/TCPSocket/d' clamd.conf > bak.conf
sed '/TCPAddr/d' bak.conf > client-$1-$2.conf
echo "Generate client-$1-$2.conf: client IP: $IP, PORT: $2"
echo "TCPAddr $IP" >> client-$1-$2.conf
echo "TCPSocket $2" >> client-$1-$2.conf
rm bak.conf

cd $CURPATH
